### ISSUE TITLE
Estrutura dos dados e funções

### ISSUE THREAD

**Issue by RafaelANTVS** [wuigamerbr/testando#3]
- [x] Criar arquivos.c e .h
- [x] Implementar struct tarefa com prioridade (int), categoria (char 100) e descrição (char[100])
- [x] Implementar enum com tipos de erro
- [x] Definir assinaturas das funçoes no ,h
- [x] Implementar funções no .c fazendo apenas o print com o nome da função chamada
- [x] Alterar função main para chamar funções implementadas

**Comment by wuigamerbr** [comment]
feito
